---
#Main installation actions

- name: Install vector dist
  become: true
  ansible.builtin.yum:
    name: "{{ vector_distrib }}"

- name: Create vector config
  become: true
  ansible.builtin.template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
    owner: root
    group: wheel
    mode: '755'