---
# tasks file for vector
- name: Info
  ansible.builtin.debug:
    var: ansible_pkg_mgr

- name: 'Include OS Family Specific Variables'
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
        - 'empty.yml'
      paths:
        - 'vars'

- name: Download vector
  ansible.builtin.get_url:
    url: "{{ vector_url }}"
    dest: "{{ vector_distrib }}"

- name: Include pkg_mgr
  include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: [install]
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'

# - name: Install vector dist
#   become: true
#   ansible.builtin.yum:
#     name: "{{ vector_distrib }}"

# - name: Create vector config
#   become: true
#   ansible.builtin.template:
#     src: vector.toml.j2
#     dest: /etc/vector/vector.toml
#     owner: root
#     group: wheel
#     mode: '755'

- name: Validate vector config
  become: true
  ansible.builtin.command: "vector validate"
  changed_when: false

- name: "Get vector version"
  ansible.builtin.command: "vector --version"
  changed_when: false

- name: Enable vector service
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted
  when: ansible_facts['virtualization_type'] != 'docker'