---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   ansible-lint .
#   yamllint .
platforms:
  - name: instance
    image: pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  # inventory:
  #   links:
  #     hosts: ../../defaults/main.yml
  #     group_vars: ../../defaults/main.yml
  #     host_vars: ../../defaults/main.yml
verifier:
  name: ansible
