---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true


  - name: Add common Verify
    import_tasks: "../common_verify/verify.yml"